import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { ArrowLeft, Calculator, IndianRupee, Percent, Calendar, Download } from "lucide-react";
import Footer from "@/components/Footer";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

const EMICalculator = () => {
  const navigate = useNavigate();
  const [loanAmount, setLoanAmount] = useState(1000000);
  const [downPayment, setDownPayment] = useState(0);
  const [rate, setRate] = useState(8.5);
  const [tenureYears, setTenureYears] = useState(1);
  const [tenureMonths, setTenureMonths] = useState(0);

  // Calculate actual principal after down payment
  const principal = loanAmount - downPayment;
  const totalTenureMonths = tenureYears * 12 + tenureMonths;

  // EMI Calculation
  const monthlyRate = rate / 12 / 100;
  const emi = principal > 0 && totalTenureMonths > 0
    ? principal * monthlyRate * Math.pow(1 + monthlyRate, totalTenureMonths) / (Math.pow(1 + monthlyRate, totalTenureMonths) - 1)
    : 0;
  const totalAmount = emi * totalTenureMonths;
  const totalInterest = totalAmount - principal;

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(amount);
  };

  const interestPercentage = totalAmount > 0 ? (totalInterest / totalAmount) * 100 : 0;
  const principalPercentage = totalAmount > 0 ? (principal / totalAmount) * 100 : 0;

  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFillColor(212, 175, 55);
    doc.rect(0, 0, pageWidth, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('EMI Calculator Report', pageWidth / 2, 18, { align: 'center' });
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, 26, { align: 'center' });

    doc.setTextColor(0, 0, 0);

    autoTable(doc, {
      startY: 45,
      head: [['Parameter', 'Value']],
      body: [
        ['Loan Amount', formatCurrency(loanAmount)],
        ['Down Payment', formatCurrency(downPayment)],
        ['Principal (After Down Payment)', formatCurrency(principal)],
        ['Interest Rate', `${rate}% p.a.`],
        ['Tenure', `${tenureYears} years ${tenureMonths} months`],
      ],
      theme: 'striped',
      headStyles: { fillColor: [212, 175, 55] },
    });

    let currentY = (doc as any).lastAutoTable?.finalY + 15 || 100;
    
    autoTable(doc, {
      startY: currentY,
      head: [['EMI Summary', 'Amount']],
      body: [
        ['Monthly EMI', formatCurrency(emi)],
        ['Total Interest', formatCurrency(totalInterest)],
        ['Total Amount Payable', formatCurrency(totalAmount + downPayment)],
        ['Principal %', `${principalPercentage.toFixed(1)}%`],
        ['Interest %', `${interestPercentage.toFixed(1)}%`],
      ],
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
    });

    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by ABC - AI Legal & Tax Co-pilot', pageWidth / 2, 285, { align: 'center' });

    doc.save(`EMI_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success("PDF exported successfully!");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-muted/30 to-background">
      {/* Header */}
      <header className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-40">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="icon" onClick={() => navigate("/")}>
                <ArrowLeft className="h-5 w-5" />
              </Button>
              <div>
                <h1 className="text-2xl font-bold text-primary flex items-center gap-2">
                  <Calculator className="w-6 h-6" />
                  EMI Calculator
                </h1>
                <p className="text-sm text-muted-foreground">Calculate your Equated Monthly Installment</p>
              </div>
            </div>
            <Button onClick={exportToPDF} className="gap-2">
              <Download className="h-4 w-4" />
              <span className="hidden sm:inline">Export PDF</span>
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
          {/* Input Section */}
          <Card className="border-2">
            <CardHeader>
              <CardTitle>Loan Details</CardTitle>
              <CardDescription>Enter your loan parameters</CardDescription>
            </CardHeader>
            <CardContent className="space-y-8">
              {/* Loan Amount */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="flex items-center gap-2">
                    <IndianRupee className="w-4 h-4" />
                    Total Loan Amount
                  </Label>
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-muted-foreground">₹</span>
                    <Input
                      type="number"
                      value={loanAmount}
                      onChange={(e) => setLoanAmount(Number(e.target.value))}
                      className="w-32 text-right"
                    />
                  </div>
                </div>
                <Slider
                  value={[loanAmount]}
                  onValueChange={(v) => setLoanAmount(v[0])}
                  min={100000}
                  max={50000000}
                  step={50000}
                  className="w-full"
                />
                <div className="flex justify-between text-xs text-muted-foreground">
                  <span>₹1L</span>
                  <span>₹5Cr</span>
                </div>
              </div>

              {/* Down Payment */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="flex items-center gap-2">
                    <IndianRupee className="w-4 h-4" />
                    Down Payment
                  </Label>
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-muted-foreground">₹</span>
                    <Input
                      type="number"
                      value={downPayment}
                      onChange={(e) => setDownPayment(Math.min(loanAmount, Number(e.target.value)))}
                      className="w-32 text-right"
                    />
                  </div>
                </div>
                <Slider
                  value={[downPayment]}
                  onValueChange={(v) => setDownPayment(v[0])}
                  min={0}
                  max={loanAmount}
                  step={10000}
                  className="w-full"
                />
                <div className="flex justify-between text-xs text-muted-foreground">
                  <span>₹0</span>
                  <span>{formatCurrency(loanAmount)}</span>
                </div>
                {downPayment > 0 && (
                  <p className="text-xs text-muted-foreground">
                    Loan Principal: <span className="font-medium text-primary">{formatCurrency(principal)}</span>
                  </p>
                )}
              </div>

              {/* Interest Rate */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="flex items-center gap-2">
                    <Percent className="w-4 h-4" />
                    Interest Rate (p.a.)
                  </Label>
                  <div className="flex items-center gap-2">
                    <Input
                      type="number"
                      value={rate}
                      onChange={(e) => setRate(Number(e.target.value))}
                      className="w-20 text-right"
                      step={0.1}
                    />
                    <span className="text-sm text-muted-foreground">%</span>
                  </div>
                </div>
                <Slider
                  value={[rate]}
                  onValueChange={(v) => setRate(v[0])}
                  min={1}
                  max={30}
                  step={0.1}
                  className="w-full"
                />
                <div className="flex justify-between text-xs text-muted-foreground">
                  <span>1%</span>
                  <span>30%</span>
                </div>
              </div>

              {/* Tenure */}
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Label className="flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    Loan Tenure
                  </Label>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Input
                        type="number"
                        value={tenureYears}
                        onChange={(e) => setTenureYears(Math.max(0, Math.min(30, Number(e.target.value))))}
                        className="text-right"
                        min={0}
                        max={30}
                      />
                      <span className="text-sm text-muted-foreground whitespace-nowrap">Years</span>
                    </div>
                    <Slider
                      value={[tenureYears]}
                      onValueChange={(v) => setTenureYears(v[0])}
                      min={0}
                      max={30}
                      step={1}
                      className="w-full"
                    />
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Input
                        type="number"
                        value={tenureMonths}
                        onChange={(e) => setTenureMonths(Math.max(0, Math.min(11, Number(e.target.value))))}
                        className="text-right"
                        min={0}
                        max={11}
                      />
                      <span className="text-sm text-muted-foreground whitespace-nowrap">Months</span>
                    </div>
                    <Slider
                      value={[tenureMonths]}
                      onValueChange={(v) => setTenureMonths(v[0])}
                      min={0}
                      max={11}
                      step={1}
                      className="w-full"
                    />
                  </div>
                </div>
                <p className="text-xs text-muted-foreground text-center">
                  Total: {tenureYears} years {tenureMonths} months ({totalTenureMonths} months)
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Results Section */}
          <div className="space-y-6">
            {/* EMI Result Card */}
            <Card className="border-2 bg-gradient-to-br from-primary/5 to-accent/5">
              <CardHeader>
                <CardTitle className="text-center">Monthly EMI</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-5xl font-bold text-center text-primary mb-2">
                  {formatCurrency(emi)}
                </div>
                <p className="text-center text-muted-foreground">per month for {totalTenureMonths} months</p>
              </CardContent>
            </Card>

            {/* Breakdown Card */}
            <Card className="border-2">
              <CardHeader>
                <CardTitle>Payment Breakdown</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Visual Bar */}
                <div className="h-8 rounded-full overflow-hidden flex">
                  <div 
                    className="bg-primary transition-all duration-500"
                    style={{ width: `${principalPercentage}%` }}
                  />
                  <div 
                    className="bg-accent transition-all duration-500"
                    style={{ width: `${interestPercentage}%` }}
                  />
                </div>

                {/* Legend */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-lg bg-primary/10 border border-primary/20">
                    <div className="flex items-center gap-2 mb-1">
                      <div className="w-3 h-3 rounded-full bg-primary" />
                      <span className="text-sm text-muted-foreground">Principal</span>
                    </div>
                    <p className="text-xl font-bold">{formatCurrency(principal)}</p>
                    <p className="text-xs text-muted-foreground">{principalPercentage.toFixed(1)}%</p>
                  </div>
                  <div className="p-4 rounded-lg bg-accent/10 border border-accent/20">
                    <div className="flex items-center gap-2 mb-1">
                      <div className="w-3 h-3 rounded-full bg-accent" />
                      <span className="text-sm text-muted-foreground">Interest</span>
                    </div>
                    <p className="text-xl font-bold">{formatCurrency(totalInterest)}</p>
                    <p className="text-xs text-muted-foreground">{interestPercentage.toFixed(1)}%</p>
                  </div>
                </div>

                {/* Down Payment Info */}
                {downPayment > 0 && (
                  <div className="p-4 rounded-lg bg-green-500/10 border border-green-500/20">
                    <div className="flex justify-between items-center">
                      <span className="text-muted-foreground">Down Payment</span>
                      <span className="text-lg font-bold text-green-600">{formatCurrency(downPayment)}</span>
                    </div>
                  </div>
                )}

                {/* Total */}
                <div className="p-4 rounded-lg bg-muted border">
                  <div className="flex justify-between items-center">
                    <span className="text-muted-foreground">Total Amount Payable</span>
                    <span className="text-2xl font-bold">{formatCurrency(totalAmount + downPayment)}</span>
                  </div>
                  {downPayment > 0 && (
                    <p className="text-xs text-muted-foreground mt-1">
                      (EMI Total: {formatCurrency(totalAmount)} + Down Payment: {formatCurrency(downPayment)})
                    </p>
                  )}
                </div>

                {/* Summary */}
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Tenure:</span>
                    <span className="font-medium">{tenureYears} yrs {tenureMonths} months</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Interest Rate:</span>
                    <span className="font-medium">{rate}% p.a.</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default EMICalculator;
