import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ExportSection {
  title: string;
  /** Key-value pairs displayed as a 2-column table */
  keyValues?: [string, string][];
  /** Full table with header row */
  table?: {
    head: string[];
    body: string[][];
    foot?: string[];
  };
  /** Plain text paragraphs */
  paragraphs?: string[];
}

export interface ExportConfig {
  /** Report title shown in header */
  title: string;
  /** Optional subtitle line */
  subtitle?: string;
  /** File name prefix (no extension) */
  fileNamePrefix: string;
  /** Header color [R, G, B] – defaults to gold [212, 175, 55] */
  headerColor?: [number, number, number];
  /** Sections of data to export */
  sections: ExportSection[];
  /** Optional footer disclaimer text */
  disclaimer?: string;
}

// ─── Formatting helpers ──────────────────────────────────────────────────────

export const formatINR = (amount: number, decimals = 0): string =>
  `₹${amount.toLocaleString('en-IN', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;

export const formatINRCompact = (amount: number): string => {
  if (amount >= 10_000_000) return `₹${(amount / 10_000_000).toFixed(2)} Cr`;
  if (amount >= 100_000) return `₹${(amount / 100_000).toFixed(2)} L`;
  return `₹${amount.toLocaleString('en-IN')}`;
};

const today = () => new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
const fileDate = () => new Date().toISOString().split('T')[0];

// ─── PDF Export ──────────────────────────────────────────────────────────────

export const exportToPDF = (config: ExportConfig): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const [hr, hg, hb] = config.headerColor || [212, 175, 55];

  // Header band
  doc.setFillColor(hr, hg, hb);
  doc.rect(0, 0, pageWidth, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(config.title, pageWidth / 2, 14, { align: 'center' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const subLine = config.subtitle ? `${config.subtitle}  |  ${today()}` : `Generated: ${today()}`;
  doc.text(subLine, pageWidth / 2, 24, { align: 'center' });

  doc.setTextColor(0, 0, 0);
  let curY = 40;

  const ensureSpace = (needed: number) => {
    if (curY + needed > doc.internal.pageSize.getHeight() - 25) {
      doc.addPage();
      curY = 20;
    }
  };

  config.sections.forEach((section) => {
    ensureSpace(30);

    // Section heading
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, 14, curY);
    curY += 5;

    // Key-value pairs
    if (section.keyValues?.length) {
      autoTable(doc, {
        startY: curY,
        body: section.keyValues,
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 70 },
          1: { cellWidth: 100 },
        },
      });
      curY = (doc as any).lastAutoTable?.finalY + 6 || curY + 30;
    }

    // Full table
    if (section.table) {
      const tableOpts: any = {
        startY: curY,
        head: [section.table.head],
        body: section.table.body,
        theme: 'striped',
        headStyles: { fillColor: [hr, hg, hb], textColor: [255, 255, 255], fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 4 },
      };
      if (section.table.foot) {
        tableOpts.foot = [section.table.foot];
        tableOpts.footStyles = { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' };
      }
      autoTable(doc, tableOpts);
      curY = (doc as any).lastAutoTable?.finalY + 6 || curY + 40;
    }

    // Paragraphs
    if (section.paragraphs?.length) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      section.paragraphs.forEach((p) => {
        ensureSpace(10);
        const lines = doc.splitTextToSize(p, pageWidth - 28);
        doc.text(lines, 14, curY);
        curY += lines.length * 5 + 3;
      });
    }

    curY += 4;
  });

  // Footer on every page
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerY = doc.internal.pageSize.getHeight() - 12;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      config.disclaimer || 'This is a computer-generated report. No signature required.',
      pageWidth / 2,
      footerY,
      { align: 'center' }
    );
    doc.text('Generated by ABC - AI Legal & Tax Co-pilot', pageWidth / 2, footerY + 5, { align: 'center' });
  }

  doc.save(`${config.fileNamePrefix}_${fileDate()}.pdf`);
};

// ─── Excel Export ────────────────────────────────────────────────────────────

export const exportToExcel = (config: ExportConfig): void => {
  const wb = XLSX.utils.book_new();

  config.sections.forEach((section, idx) => {
    const sheetData: string[][] = [];

    // Section title row
    sheetData.push([section.title]);
    sheetData.push([]);

    if (section.keyValues?.length) {
      section.keyValues.forEach(([k, v]) => sheetData.push([k, v]));
      sheetData.push([]);
    }

    if (section.table) {
      sheetData.push(section.table.head);
      section.table.body.forEach((row) => sheetData.push(row));
      if (section.table.foot) sheetData.push(section.table.foot);
      sheetData.push([]);
    }

    if (section.paragraphs?.length) {
      section.paragraphs.forEach((p) => sheetData.push([p]));
    }

    // Sheet name (max 31 chars, unique)
    const sheetName = section.title.substring(0, 28) || `Sheet${idx + 1}`;
    const ws = XLSX.utils.aoa_to_sheet(sheetData);

    // Auto-size columns
    const maxCols = Math.max(...sheetData.map((r) => r.length));
    ws['!cols'] = Array.from({ length: maxCols }, (_, ci) => ({
      wch: Math.max(12, ...sheetData.map((r) => (r[ci] || '').length + 2)),
    }));

    XLSX.utils.book_append_sheet(wb, ws, sheetName);
  });

  XLSX.writeFile(wb, `${config.fileNamePrefix}_${fileDate()}.xlsx`);
};

// ─── Word Export (HTML-based .doc) ───────────────────────────────────────────

export const exportToWord = (config: ExportConfig): void => {
  const [hr, hg, hb] = config.headerColor || [212, 175, 55];
  const headerHex = `#${hr.toString(16).padStart(2, '0')}${hg.toString(16).padStart(2, '0')}${hb.toString(16).padStart(2, '0')}`;

  let html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="utf-8">
    <style>
      body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #222; margin: 24px; }
      .header { background: ${headerHex}; color: white; padding: 16px 24px; margin: -24px -24px 24px; }
      .header h1 { font-size: 20pt; margin: 0 0 4px; }
      .header p { font-size: 10pt; margin: 0; opacity: 0.9; }
      h2 { font-size: 14pt; color: #333; border-bottom: 2px solid ${headerHex}; padding-bottom: 4px; margin-top: 24px; }
      table { border-collapse: collapse; width: 100%; margin: 8px 0 16px; }
      th { background: ${headerHex}; color: white; }
      th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 10pt; }
      tr:nth-child(even) { background: #f9f9f9; }
      .kv td:first-child { font-weight: bold; width: 35%; background: #f5f5f5; }
      .footer { margin-top: 32px; font-size: 8pt; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 8px; }
      p.para { font-size: 10pt; margin: 4px 0; }
    </style></head><body>
    <div class="header">
      <h1>${config.title}</h1>
      <p>${config.subtitle ? `${config.subtitle} | ` : ''}Generated: ${today()}</p>
    </div>`;

  config.sections.forEach((section) => {
    html += `<h2>${section.title}</h2>`;

    if (section.keyValues?.length) {
      html += `<table class="kv">`;
      section.keyValues.forEach(([k, v]) => {
        html += `<tr><td>${k}</td><td>${v}</td></tr>`;
      });
      html += `</table>`;
    }

    if (section.table) {
      html += `<table><thead><tr>`;
      section.table.head.forEach((h) => (html += `<th>${h}</th>`));
      html += `</tr></thead><tbody>`;
      section.table.body.forEach((row) => {
        html += `<tr>`;
        row.forEach((cell) => (html += `<td>${cell}</td>`));
        html += `</tr>`;
      });
      if (section.table.foot) {
        html += `<tr style="font-weight:bold;background:#f0f0f0">`;
        section.table.foot.forEach((cell) => (html += `<td>${cell}</td>`));
        html += `</tr>`;
      }
      html += `</tbody></table>`;
    }

    if (section.paragraphs?.length) {
      section.paragraphs.forEach((p) => (html += `<p class="para">${p}</p>`));
    }
  });

  html += `<div class="footer">
    <p>${config.disclaimer || 'This is a computer-generated report. No signature required.'}</p>
    <p>Generated by ABC - AI Legal & Tax Co-pilot</p>
  </div></body></html>`;

  const blob = new Blob(['\ufeff', html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${config.fileNamePrefix}_${fileDate()}.doc`;
  a.click();
  URL.revokeObjectURL(url);
};
